const jobTitle = Object.freeze([,
  '3D Animator',
  'Academic Advisor',
  'Account Manager',
  'Accountant',
  'Actor/Actress',
  'Acupuncturist',
  'Administrative Assistant',
  'Advertising Coordinator',
  'Aerospace Engineer',
  'Aerospace Technician',
  'Agricultural Scientist',
  'Agronomist',
  'Air Traffic Controller',
  'Airline Pilot',
  'Analyst (Business, Data, Financial)',
  'Android Developer',
  'Animal Trainer',
  'Animator',
  'App Developer',
  'Archaeologist',
  'Architect',
  'Architectural Drafter',
  'Art Director',
  'Art Therapist',
  'Artist',
  'Assembly Line Worker',
  'Astrophysicist',
  'Attorney',
  'Auctioneer',
  'Auditor',
  'Auto Mechanic',
  'Baker',
  'Bakers Assistant',
  'Bank Teller',
  'Bar Manager',
  'Barista',
  'Bartender',
  'Benefits Administrator',
  'Bioinformatician',
  'Biomedical Engineer',
  'Biostatistician',
  'Blockchain Developer',
  'Blogger',
  'Bookkeeper',
  'Brand Ambassador',
  'Brand Manager',
  'Broadcast Journalist',
  'Business Analyst',
  'Butcher',
  'CAD Designer',
  'CNC Operator',
  'Call Center Operator',
  'Car Salesperson',
  'Carpenter',
  'Cartographer',
  'Certified Nursing Assistant',
  'Chef',
  'Chemist',
  'Chief Information Officer (CIO)',
  'Chief Operating Officer (COO)',
  'Chief Technology Officer (CTO)',
  'Chiropractor',
  'Cinematographer',
  'City Planner',
  'Civil Engineer',
  'Claims Adjuster',
  'Clinical Psychologist',
  'Clinical Research Coordinator',
  'Cloud Architect',
  'Commercial Pilot',
  'Communications Manager',
  'Community Health Worker',
  'Compliance Officer',
  'Computer Programmer',
  'Conservationist',
  'Construction Manager',
  'Content Strategist',
  'Content Writer',
  'Copywriter',
  'Cost Estimator',
  'Court Reporter',
  'Cryptographer',
  'Customer Service Representative',
  'Customer Support Specialist',
  'Data Engineer',
  'Data Entry Clerk',
  'Data Scientist',
  'Database Administrator',
  'Dental Assistant',
  'Dental Hygienist',
  'Dermatologist',
  'Design Engineer',
  'Desktop Support Technician',
  'DevOps Engineer',
  'Developer (Web Developer, Software Developer)',
  'Dietitian',
  'Digital Analyst',
  'Digital Artist',
  'Digital Content Manager',
  'Digital Forensic Analyst',
  'Digital Marketing Specialist',
  'Diver',
  'Diversity and Inclusion Specialist',
  'Doctor',
  'Drone Pilot',
  'E-Learning Developer',
  'E-commerce Manager',
  'Ecologist',
  'Economist',
  'Electrical Engineer',
  'Electrician',
  'Electronic Technician',
  'Emergency Medical Technician (EMT)',
  'Employment Counselor',
  'Energy Analyst',
  'Energy Auditor',
  'Environmental Engineer',
  'Environmental Planner',
  'Environmental Scientist',
  'Equity Research Analyst',
  'Ethical Hacker',
  'Event Coordinator',
  'Event Photographer',
  'Event Planner',
  'Executive Assistant',
  'Executive Chef',
  'Exercise Physiologist',
  'Exhibition Designer',
  'FPGA Engineer',
  'Farmer',
  'Fashion Buyer',
  'Fashion Designer',
  'Field Sales Representative',
  'Film Editor',
  'Financial Advisor',
  'Financial Analyst',
  'Fire Chief',
  'Firefighter',
  'Fitness Instructor',
  'Fitness Trainer',
  'Flavorist',
  'Flight Attendant',
  'Flight Engineer',
  'Forensic Accountant',
  'Forensic Scientist',
  'Front Office Manager',
  'Front-End Developer',
  'Fundraiser',
  'GIS Analyst',
  'GIS Specialist',
  'Game Developer',
  'Genealogist',
  'Genetic Counselor',
  'Geographer',
  'Geologist',
  'Glassblower',
  'Grant Manager',
  'Grant Writer',
  'Graphic Designer',
  'Graphic Illustrator',
  'Green Building Consultant',
  'Greenhouse Grower',
  'HR Manager',
  'HVAC Technician',
  'Hardware Engineer',
  'Headhunter',
  'Health Educator',
  'Health and Safety Officer',
  'Hedge Fund Manager',
  'Home Health Aide',
  'Horticulturist',
  'Hotel Manager',
  'Human Resources Coordinator',
  'Human Resources Generalist',
  'IT Auditor',
  'IT Business Analyst',
  'IT Consultant',
  'IT Project Manager',
  'IT Security Analyst',
  'Immunologist',
  'Incident Responder',
  'Industrial Designer',
  'Industrial Hygienist',
  'Information Architect',
  'Information Security Analyst',
  'Infrastructure Architect',
  'Inside Sales Manager',
  'Inside Sales Representative',
  'Instructional Designer',
  'Instructional Technologist',
  'Insurance Underwriter',
  'Integration Engineer',
  'Intellectual Property Attorney',
  'Interior Decorator',
  'Interior Designer',
  'Inventory Control Specialist',
  'Investment Banker',
  'Java Architect',
  'Java Developer',
  'Jazz Musician',
  'Jockey',
  'Journal Editor',
  'Journalist',
  'Judge',
  'Judicial Clerk',
  'Lab Manager',
  'Laboratory Assistant',
  'Laboratory Technician',
  'Landscape Architect',
  'Landscape Designer',
  'Learning and Development Specialist',
  'Legal Assistant',
  'Legal Secretary',
  'Legislative Assistant',
  'Librarian',
  'Life Coach',
  'Linux Administrator',
  'Loan Officer',
  'Logistician',
  'Machine Learning Engineer',
  'Machine Operator',
  'Makeup Artist',
  'Management Consultant',
  'Manufacturing Engineer',
  'Market Analyst',
  'Market Research Analyst',
  'Marketing Manager',
  'Massage Therapist',
  'Materials Scientist',
  'Math teacher',
  'Mechanic',
  'Mechanical Designer',
  'Media Buyer',
  'Medical Billing Specialist',
  'Medical Illustrator',
  'Medical Librarian',
  'Medical Technologist',
  'Mental Health Counselor',
  'Merchandiser',
  'Mergers and Acquisitions Analyst',
  'Metadata Librarian',
  'Meteorological Technician',
  'Meteorologist',
  'Microbiologist',
  'Microstrategy Developer',
  'Mobile App Developer',
  'Mobile Application Tester',
  'Multimedia Artist',
  'Multimedia Developer',
  'Musician',
  'Network Administrator',
  'Network Engineer',
  'Network Security Engineer',
  'Neurologist',
  'Neuroscientist',
  'Nuclear Engineer',
  'Nuclear Physicist',
  'Nurse Anesthetist',
  'Nurse',
  'Nutrition Consultant',
  'Nutritionist',
  'Occupational Health Nurse',
  'Occupational Health and Safety Specialist',
  'Occupational Therapist Assistant',
  'Occupational Therapist Assistant',
  'Occupational Therapist',
  'Office Manager',
  'Online Community Manager',
  'Online Marketing Manager',
  'Operating Room Nurse',
  'Operating Room Technician',
  'Operations Manager',
  'Optical Engineer',
  'Optician',
  'Optometrist',
  'Oracle Database Administrator',
  'Order Picker',
  'Outreach Coordinator',
  'Outreach Specialist',
  'PR Specialist',
  'Packaging Engineer',
  'Painter',
  'Paralegal',
  'Paraprofessional Educator',
  'Park Ranger',
  'Patent Attorney',
  'Payroll Specialist',
  'Pediatrician',
  'Personal Trainer',
  'Petroleum Engineer',
  'Pharmaceutical Sales Representative',
  'Pharmacist',
  'Pharmacy Technician',
  'Photographer',
  'Photojournalist',
  'Physical Therapist',
  'Physical Therapy Assistant',
  'Physician Assistant',
  'Physician Liaison',
  'Physicist',
  'Pilot',
  'Plant Manager',
  'Plumber',
  'Plumbing Engineer',
  'Police Detective',
  'Police Officer',
  'Portfolio Manager',
  'Postdoctoral Researcher',
  'Power Plant Operator',
  'Pricing Analyst',
  'Private Investigator',
  'Product Manager',
  'Product Owner',
  'Production Manager',
  'Professor',
  'Project Coordinator',
  'Project Manager',
  'Proofreader',
  'Property Manager',
  'Psychiatric Nurse',
  'Psychologist',
  'Public Relations Specialist',
  'Publicist',
  'Quality Assurance Tester',
  'Radiation Therapist',
  'Real Estate Agent',
  'Real Estate Developer',
  'Receptionist',
  'Receptionist',
  'Recruitment Specialist',
  'Regulatory Affairs Specialist',
  'Rehabilitation Counselor',
  'Research Analyst',
  'Research Scientist',
  'Respiratory Therapist',
  'Respiratory Therapist',
  'Risk Analyst',
  'Robotics Engineer',
  'SEO Specialist',
  'Sales Engineer',
  'Sales Representative',
  'School Counselor',
  'School Principal',
  'Science Writer',
  'Semi Truck Driver',
  'Server Administrator',
  'Set Designer',
  'Social Media Coordinator',
  'Social Media Manager',
  'Software Engineer',
  'Software Tester',
  'Solar Energy Systems Engineer',
  'Solution Engineer',
  'Sound Engineer',
  'Special Education Teacher',
  'Speech Pathologist',
  'Speech-Language Pathologist',
  'Sports Agent',
  'Sports Coach',
  'Sports Photographer',
  'Statistician',
  'Structural Engineer',
  'Surgeon',
  'Systems Administrator',
  'Systems Analyst',
  'Tax Accountant',
  'Tax Consultant',
  'Tax Preparer',
  'Taxi Driver',
  'Teacher',
  'Technical Recruiter',
  'Technical Support Engineer',
  'Technical Support Specialist',
  'Technical Writer',
  'Telecommunications Engineer',
  'Telemarketer',
  'Textile Designer',
  'Tour Guide',
  'Tour Manager',
  'Toxicologist',
  'Trade Analyst',
  'Traffic Engineer',
  'Transit Bus Driver',
  'Translator',
  'Travel Agent',
  'UI/UX Designer',
  'UX Researcher',
  'UX/UI Designer',
  'Underwriter',
  'Urban Planner',
  'Validation Engineer',
  'Veterinarian',
  'Veterinary Technician',
  'Video Game Designer',
  'Videographer',
  'Virtual Assistant',
  'Visual Merchandiser',
  'Voice Actor',
  'Web Content Manager',
  'Web Designer',
  'Wedding Planner',
  'Welder',
  'Wellness Coordinator',
  'Wildlife Biologist',
  'Wind Energy Engineer',
  'Winemaker',
  'WordPress Developer',
  'Workplace Safety Specialist',
  'Yoga Instructor',
  'Youth Counselor',
  'Zoologist',
  'iOS Developer'
]);

module.exports = jobTitle;
