const usUniversity = Object.freeze([
  'A.T. Still University',
  'AIB College of Business',
  'ASA College',
  'ATI College',
  'Abilene Christian University',
  'Academy of Arts University',
  'Acupuncture & Integrative Medicine College',
  'Acupuncture Massage College',
  'Adams State University',
  'Adance Computing Institute',
  'Adelphi University',
  'Adrian College',
  'Agnes Scott College',
  'Aims Community College',
  'Alabama A&M University',
  'Alamance Community College',
  'Alamo Colleges',
  'Alaska Christian College',
  'Albany Technical College',
  'Albertus Magnus College',
  'Albion College',
  'Alcorn State University',
  'Alexandria Technical & Community College',
  'Alfred University',
  'Allan Hancock College',
  'Allegheny College',
  'Alliant International University',
  'Allied American University',
  'Alma College',
  'Alpena Community College',
  'Alvernia University',
  'Alverno College',
  'Alvin Community College',
  'American Public University System',
  'American University',
  'Amherst College',
  'Anabaptist Mennonite Biblical Seminary',
  'Anaheim University',
  'Anderson University',
  'Anderson University',
  'Andrews University',
  'Angeles College',
  'Angelo State University',
  'Anne Arundel Community College',
  'Anoka-Ramsey Community College',
  'Antelope Valley College',
  'Antioch University Los Angeles',
  'Antioch University New England',
  'Appalachian State University',
  'Aquinas College',
  'Aquinas Institute of Theology',
  'Arapahoe Community College',
  'Arcadia University',
  'Argosy University',
  'Arizona State University',
  'Arizona Western College',
  'Arkansas Northeastern College',
  'Arkansas State University',
  'Arkansas Tech University',
  'Armstrong Atlantic State University',
  'Art Center College of Design',
  'Asbury University',
  'Asheville-Buncombe Technical Community College',
  'Ashford University',
  'Ashland University',
  'Asnuntuck Community College',
  'Assemblies of God Theological Seminary',
  'Assumption College',
  'Athens State University',
  'Atlanta Metropolitan State College',
  'Atlanta Technical College',
  'Atlanta’s John Marshall Law School',
  'Atlantic Cape Community College',
  'Atlantic Institute of Oriental Medicine',
  'Auburn University at Montgomery',
  'Auburn University',
  'Augsburg College',
  'Augusta University',
  'Augustana College',
  'Aultman College of Nursing and Health Sciences',
  'Auraria Higher Education Center',
  'Aurora University',
  'Austin College',
  'Austin Community College District',
  'Austin Graduate School of Theology',
  'Austin Peay State University',
  'Averett University',
  'Avila University',
  'Babson College',
  'Baker College',
  'Bakersfield College',
  'Baldwin Wallace University',
  'Ball State University',
  'Baltimore City Community College',
  'Baptist Bible College & Seminary',
  'Baptist Health System School of Health Professions',
  'Bard College',
  'Barnard College',
  'Barry University',
  'Barstow Community College',
  'Bates College',
  'Bay College',
  'Baylor University',
  'Belhaven University',
  'Bellarmine University',
  'Bellevue College',
  'Bellevue University',
  'Belmont College',
  'Belmont University',
  'Bemidji State University',
  'Benedictine College',
  'Benedictine University',
  'Bennington College',
  'Bentley University',
  'Berea College',
  'Bergen Community College',
  'Berkeley City College',
  'Berkeley University of California',
  'Berklee College of Music',
  'Berkshire Community College',
  'Berry College',
  'Bethel College Indiana',
  'Bethel University',
  'Bethune-Cookman University',
  'Big Bend Community College',
  'Binghamton University',
  'Birmingham-Southern College',
  'Black Hills State University',
  'Blackfeet Community College',
  'Bladen Community College',
  'Blinn College',
  'Bloomsburg University',
  'Blue Mountain Community College',
  'Bob Jones University',
  'Body Therapy Institute',
  'Boise State University',
  'Bossier Parish Community College',
  'Boston Architectural College',
  'Boston College',
  'Boston University',
  'Bowdoin College',
  'Bowie State University',
  'Bowling Green State University',
  'Bradley University',
  'Brandeis University',
  'Brandman University',
  'Brazosport College',
  'Bridgewater State University',
  'Brigham Young University Hawaii',
  'Brigham Young University Idaho',
  'Brigham Young University',
  'Brookdale Community College',
  'Brookhaven College',
  'Broward College',
  'Brown Mackie College',
  'Brown University',
  'Bryan College of Health Sciences',
  'Bryan College',
  'Bryan University',
  'Bryant University',
  'Bryn Mawr College',
  'Bucknell University',
  'Bucks County Community College',
  'Buffalo State University',
  'Burlington County College',
  'Butler Community College',
  'Butler County Community College',
  'Butler University',
  'Butte College',
  'Cabrillo College',
  'Calhoun Community College',
  'California Baptist University',
  'California College of the Arts',
  'California Community Colleges Chanellor’s Office',
  'California Institute of Integral Studies',
  'California Institute of Technology',
  'California Institute of the Arts',
  'California Lutheran University',
  'California Miramar University',
  'California Polytechnic State University',
  'California State Polytechnic University Pomona',
  'California State University Bakersfield',
  'California State University Channel Islands',
  'California State University Dominguez Hills',
  'California State University East Bay',
  'California State University Fullerton',
  'California State University Long Beach',
  'California State University Monterey Bay',
  'California State University Northridge',
  'California State University Sacramento',
  'California State University San Bernardino',
  'California State University San Marcos',
  'California State University Stanislaus',
  'California State University',
  'California University of Pennsylvania',
  'California Western School of Law San Diego',
  'Calvin College',
  'Cambridge College',
  'Camden County College',
  'Cameron University',
  'Campbell University',
  'Canada College',
  'Canton State University of New York',
  'Cape Fear Community College',
  'Capital University',
  'Cardinal Stritch University',
  'Career Point College',
  'Carleton College',
  'Carlos Albizu University',
  'Carlow University',
  'Carnegie Institution for Science',
  'Carnegie Mellon University',
  'Carroll College',
  'Carroll Community College',
  'Carroll University',
  'Carson-Newman University',
  'Carthage College',
  'Carver College',
  'Cascadia Community College',
  'Case Western Reserve University',
  'Casper College',
  'Castleton State College of Vermont',
  'Cazenovia College',
  'Cedar Crest College',
  'Cedar Valley College',
  'Cedarville University',
  'Centenary College of Louisiana',
  'Centenary College of New Jersey',
  'Central Arizona College',
  'Central Baptist College',
  'Central College',
  'Central Georgia Technical College',
  'Central Lakes College',
  'Central Maine Community College',
  'Central Methodist University',
  'Central Michigan University',
  'Central New Mexico',
  'Central Ohio Technical College',
  'Central Oregon Community College',
  'Central Piedmont Community College',
  'Central State University',
  'Central Texas College',
  'Central Washington University',
  'Central Wyoming College',
  'Centralia College',
  'Centre College',
  'Centura College',
  'Century College',
  'Cerritos College',
  'Cerro Coso Community College',
  'Chadron State College',
  'Chaffey College',
  'Chaminade University',
  'Champlain College',
  'Chapman University',
  'Charlotte School of Law',
  'Charter College',
  'Chatham University',
  'Chesapeake College',
  'Chestnut Hill College',
  'Cheyney University of Pennsylvania',
  'Chicago ORT Technical Institute',
  'Child Care Education Institute',
  'Chipola College',
  'Chippewa Valley Technical College',
  'Chowan University',
  'Christendom College',
  'Christian Brothers University',
  'Christopher Newport University',
  'Cincinnati College of Mortuary Science',
  'Cincinnati State Technical and Community College',
  'Citrus College',
  'City College of San Francisco',
  'City Colleges of Chicago',
  'Claremont Graduate University',
  'Claremont McKenna College',
  'Clarion University',
  'Clark College',
  'Clark University',
  'Clarkson University',
  'Clatsop Community College',
  'Clayton State University',
  'Clemson University',
  'Cleveland State University',
  'Clinton Community College',
  'Coastal Bend College',
  'Coastal Carolina University',
  'Cobleskill University',
  'Coe College',
  'Cogswell Polytechnical College',
  'Coker College',
  'Colby College',
  'Colby Sawyer College',
  'Colgate University',
  'College for Creative Studies',
  'College of Central Florida',
  'College of Charleston',
  'College of DuPage',
  'College of Environmental Science and Forestry',
  'College of Lake County',
  'College of Marin',
  'College of Saint Benedict, Saint John’s University',
  'College of San Mateo',
  'College of Southern Idaho',
  'College of Southern Maryland',
  'College of Southern Nevada',
  'College of the Atlantic',
  'College of the Canyons',
  'College of the Desert',
  'College of the Holy Cross',
  'College of the Mainland',
  'College of the Redwoods',
  'College of the Sequoias',
  'College of the Siskiyous',
  'Colorado College',
  'Colorado Heights University',
  'Colorado Mesa University',
  'Colorado School of Mines',
  'Colorado State University',
  'Colorado State University-Pueblo',
  'Columbia College Chicago',
  'Columbia College South Carolina',
  'Columbia College',
  'Columbia College',
  'Columbia International University',
  'Columbia School of English',
  'Columbia State Community College',
  'Columbia University in the City of New York',
  'Columbus State Community College',
  'Columbus State University',
  'Columbus Technical College',
  'Community College System of New Hampshire',
  'Community College of Allegheny County',
  'Community College of Aurora',
  'Community College of Denver',
  'Community College of Philadelphia',
  'Community College of Rhode Island',
  'Concord University',
  'Concordia College New York',
  'Concordia College',
  'Concordia University Nebraska',
  'Concordia University Portland Oregon',
  'Concordia University Saint Paul',
  'Concordia University Texas',
  'Connecticut College',
  'Connors State College',
  'Contra Costa College',
  'Copper Mountain College',
  'Coppin State University',
  'Cornell College',
  'Cornell University',
  'Cornerstone University',
  'Cortland College',
  'County College of Morris',
  'Covenant College',
  'Crafton Hills College',
  'Craven Community College',
  'Creighton University',
  'Crowder College',
  'Crown College',
  'Cuesta College',
  'Culinary Institute LeNotre',
  'Culinary Institute of America',
  'Culver-Stockton College',
  'Cumberland University',
  'Curry College',
  'Cuyahoga Community College',
  'Cuyamaca College',
  'Cypress College',
  'Dabney S. Lancaster Community College',
  'Dade Medical College',
  'Daemen College',
  'Dakota College at Bottineau',
  'Dakota County Technical College',
  'Dakota State University',
  'Dakota Wesleyan University',
  'Dallas Baptist University',
  'Dallas Nursing Institute',
  'Dalton State',
  'Danville Area Community College',
  'Dartmouth College',
  'Darton State College',
  'Davenport University',
  'Davidson College',
  'Daytona State College',
  'DeAnza College',
  'DePaul University',
  'DePauw University',
  'DeSales University',
  'DeVry University',
  'Defiance College',
  'Del Mar College',
  'Delaware County Community College',
  'Delaware State University',
  'Delaware Technical Community College',
  'Delaware Valley College',
  'Delhi State University of New York',
  'Delta College',
  'Delta State University',
  'Denison University',
  'Des Moines Area Community College',
  'Diablo Valley College',
  'Dickinson College',
  'DigiPen Institute of Technology',
  'Divine Word College',
  'Dixie State University',
  'Dominican College',
  'Dominican School of Philosophy and Theology',
  'Dominican University of California',
  'Dominican University',
  'Dordt College',
  'Douglas J. Aveda Institute',
  'Dowling College',
  'Drake University',
  'Drew University',
  'Drexel University College of Medicine',
  'Drexel University',
  'Drury University',
  'Duke University',
  'Duquesne University',
  'Durham Technical Community College',
  'D’Youville College',
  'Earlham College',
  'East  Central University',
  'East Carolina University',
  'East Georgia State College',
  'East Los Angeles College',
  'East Mississippi Community College',
  'East Stroudsburg University',
  'East Tennessee State University',
  'East Texas Baptist University',
  'Eastern Connecticut State University',
  'Eastern Illinois University',
  'Eastern Iowa Community Colleges',
  'Eastern Kentucky University',
  'Eastern Mennonite University',
  'Eastern Michigan University',
  'Eastern New Mexico University',
  'Eastern Oregon University',
  'Eastern University',
  'Eastern Virginia Medical School',
  'Eastern Washington University',
  'Eastern West Virgina Community and Technical College',
  'Eastwick College',
  'Eckerd College',
  'Edgewood College',
  'Edinboro University',
  'Edison State College',
  'Edmonds Community College',
  'El Camino College Compton Center',
  'El Camino College',
  'El Paso Community College',
  'Elim Bible Institute',
  'Elizabeth City State University',
  'Elizabethtown College',
  'Elmhurst College',
  'Elmira College',
  'Elms College',
  'Elon University',
  'Embry-Riddle Aeronautical University',
  'Emerson College',
  'Emmanuel College',
  'Emory University',
  'Empire State College',
  'Emporia State University',
  'Endicott College',
  'Enterprise State Community College',
  'Erie Community College State University of New York',
  'Evangel University',
  'Evangelical Seminary',
  'Everett Community College',
  'Everglades University',
  'Excelsior College',
  'Ex’pression College',
  'Fairfield University',
  'Fairleigh Dickinson University',
  'Fairmont State University',
  'Faith Evangelical College and Seminary',
  'Farmingdale State College',
  'Fashion Institute of Design & Merchandising',
  'Fashion Institute of Technology',
  'Faulkner State Community College',
  'Fayetteville Technical Community College',
  'Felician College',
  'Ferris State University',
  'Ferrum College',
  'Fielding Graduate University',
  'Finger Lakes Community College',
  'Finlandia University',
  'Fisk University',
  'Fitchburg State University',
  'Five Towns College',
  'Flagler College',
  'Flathead Valley Community College',
  'Flint Hills Technical College',
  'Florence-Darlington Technical College',
  'Florida Atlantic University',
  'Florida Gulf Coast University',
  'Florida Institute of Technology',
  'Florida International University',
  'Florida National University',
  'Florida Southern College',
  'Florida State College at Jacksonville',
  'Florida State University',
  'Fontbonne University',
  'Foothill College',
  'Foothill-De Anza Community College District',
  'Fordham University',
  'Forrest College',
  'Forsyth Technical Community College',
  'Fort Hays State University',
  'Fort Lewis College',
  'Fort Peck Community College',
  'Fort Scott Community College',
  'Fortis Institute',
  'Framingham State University',
  'Francis Marion University',
  'Franklin & Marshall College',
  'Franklin University',
  'Frederick Community College',
  'Frederick Taylor University',
  'Fredonia University',
  'Freed-Hardeman University',
  'Fresno City College',
  'Fresno Pacific University',
  'Fresno State',
  'Front Range Community College',
  'Frontier Nursing University',
  'Frostburg State University',
  'Fuller Theological Seminary',
  'Fullerton  College',
  'Furman University',
  'Gadsden State  Community College',
  'Galen College of Nursing',
  'Gallaudet University',
  'Galveston College',
  'Garden City Community College',
  'Gardner-Webb University',
  'Garrett College',
  'Gaston College',
  'Gateway Technical College',
  'Gavilan College',
  'Geneseo University',
  'Geneva College',
  'George Fox University',
  'George Mason University',
  'Georgetown College',
  'Georgetown University',
  'Georgia College',
  'Georgia Gwinnett College',
  'Georgia Institute of Technology',
  'Georgia Perimeter College',
  'Georgia South Western State University',
  'Georgia Southern University',
  'Georgia State University',
  'Georgian Court University',
  'Germanna Community College',
  'Gettysburg College',
  'Glendale Community College',
  'Glendale Community College',
  'Globe Institute of Technology',
  'Globe University',
  'Gnomon School of Visual Effects',
  'Golden Gate Baptist Theological Seminary',
  'Golden West College',
  'Goldey-Beacom College',
  'Gonzaga University',
  'Goodwin College',
  'Gordon College',
  'Gordon Conwell Theological Seminary',
  'Goshen College',
  'Goucher College',
  'Governors State',
  'Grace College and Seminary',
  'Grand Canyon University',
  'Grand Rapids Community College',
  'Grand Valley State University',
  'Granite State College',
  'Grayson College',
  'Great Basin College',
  'Green Mountain College',
  'Green River Community College',
  'Greenville College',
  'Grinnell College',
  'Grossmont College',
  'Grove City College',
  'Guilford Technical Community College',
  'Gulf Coast State College',
  'Gustavus Adolphus College',
  'Hagerstown Community  College',
  'Hamilton College',
  'Hamline University',
  'Hampden-Sydney College',
  'Hampshire College',
  'Hannibal-LaGrange',
  'Hanover College',
  'Harding University',
  'Harford Community College',
  'Harper College',
  'Harris-Stowe State University',
  'Harrisburg Area Community College',
  'Harrison College',
  'Hartford Seminary',
  'Hartnell College',
  'Hartwick College',
  'Harvard Business School',
  'Harvard University',
  'Harvey Mudd College',
  'Haverford College',
  'Hawkeye Community College',
  'Heartland Community College',
  'Heidelberg University',
  'Henderson State University',
  'Hendrix College',
  'Henley-Putnam University',
  'Henry Ford College',
  'Heritage Bible College',
  'Herkimer College',
  'Hesston College',
  'High Point University',
  'Highland Community College',
  'Highline College',
  'Hill College',
  'Hillsborough Community College',
  'Hillsdale College',
  'Hiram College',
  'Hiwassee College',
  'Hobart and William Smith Colleges',
  'Hocking College',
  'Hofstra University',
  'Holy Cross College',
  'Holy Family University',
  'Holy Names University',
  'Hood College',
  'Hope College',
  'Houston Baptist University',
  'Houston Community College',
  'Howard College',
  'Howard Community College',
  'Howard Payne University',
  'Howard University',
  'Hudson Valley Community College',
  'Humboldt State University',
  'Humphreys College',
  'Huntingdon College',
  'Huntington College of Health Sciences',
  'Husson University',
  'IIT Chicago-Kent College of Law',
  'Icahn School of Medicine at Mount Sinai',
  'Idaho State University',
  'Illinois Central College',
  'Illinois College of Optometry',
  'Illinois Institute of Technology',
  'Illinois Mathematics and Science Academy',
  'Illinois State University',
  'Illinois Valley Community College',
  'Illinois Wesleyan University',
  'Imperial Valley College',
  'Indiana State University',
  'Indiana University Bloomington',
  'Indiana University East',
  'Indiana University Northwest',
  'Indiana University South Bend',
  'Indiana University Southeast',
  'Indiana University of Pennsylvania',
  'Indiana University – Purdue University Fort Wayne',
  'Indiana University – Purdue University Indianapolis',
  'Indiana University',
  'Indiana University',
  'Indiana Wesleyan University',
  'Institute of Design and Construction',
  'Institute of Production and Recording',
  'Interactive College of Technology',
  'International Sports Sciences Association',
  'International Technological University',
  'Inver Hills Community College',
  'Iona College',
  'Iowa Central Community College',
  'Iowa State University',
  'Iowa Wesleyan College',
  'Iowa Western Community College',
  'Irvine Valley College',
  'Isothermal Community College',
  'Itawamba Community College',
  'Ithaca College',
  'Ivy Tech Community College',
  'Jackson College',
  'Jackson State Community College',
  'Jackson State University',
  'Jacksonville State University',
  'Jacksonville University',
  'James Madison University',
  'Jamestown Community College',
  'Jefferson College',
  'John A. Logan College',
  'John Brown University',
  'John Carroll University',
  'John F. Kennedy University',
  'Johns Hopkins Bloomberg School of Public Health',
  'Johns Hopkins School of Advanced International Studies',
  'Johns Hopkins University',
  'Johnson County Community College',
  'Johnson State College',
  'Johnson University',
  'Johnson and Wales University',
  'Joliet Junior College',
  'Jones International University',
  'Joseph’s College',
  'Judson University',
  'Juniata College',
  'Kalamazoo College',
  'Kalamazoo Valley Community College',
  'Kankakee Community College',
  'Kansas City Kansas Community College',
  'Kansas City University of Medicine and Biosciences',
  'Kansas State University',
  'Kaplan University',
  'Kaskaskia College',
  'Kean University',
  'Keck Graduate Institute',
  'Keene State College',
  'Keiser University',
  'Kennesaw State University',
  'Kent State University',
  'Kentucky Christian University',
  'Kentucky Community and Technical College System',
  'Kentucky State University',
  'Kenyon College',
  'Kettering College',
  'Kettering University',
  'Keuka College',
  'Keystone College',
  'King University',
  'King’s College',
  'Kirkwood Community College',
  'Kishwaukee College',
  'Knox College',
  'Kutztown University',
  'LSU Health Sciences Center – New Orleans',
  'LSU Health Sciences Center – New Orleans',
  'La Roche College',
  'La Salle University',
  'La Sierra University',
  'Lackawanna College',
  'Lafayette College',
  'Lake Erie College of Osteopathic Medicine',
  'Lake Forest College',
  'Lake Michigan College',
  'Lake Sumter State College',
  'Lake Superior State University',
  'Lake Tahoe Community College',
  'Lakeland Community College',
  'Lakeview College of Nursing',
  'Lamar Institute of Technology',
  'Lamar State College – Orange',
  'Lamar State College – Port Arthur',
  'Lamar University',
  'Lancaster Bible College',
  'Lancaster County Career and Technology Center',
  'Lancaster Theological Seminary',
  'Lander University',
  'Lane Community College',
  'Laney College',
  'Langston University',
  'Lanier Technical College',
  'Lansdale School of Business',
  'Lansing Community College',
  'Las Positas College',
  'Laurus College',
  'Lawrence Technological University',
  'Lawrence University',
  'La’ James College',
  'Le Moyne',
  'LeTourneau University',
  'Lebanon Valley College',
  'Lee University',
  'Leech Lake Tribal College',
  'Lees McRae College',
  'Lehigh Carbon Community College',
  'Lehigh University',
  'Lehman College',
  'Lenoir Community College',
  'Lesley University',
  'Lewis University',
  'Lewis and Clark Community College',
  'Lewis and Clark',
  'Liberty University',
  'Life Chiropractic College West',
  'Life University',
  'Lim College',
  'Lima Central Catholic High School',
  'Limestone College',
  'Lincoln Land Community College',
  'Lincoln Memorial University',
  'Lincoln University',
  'Lindenwood University',
  'Lindsey Wilson College',
  'Linfield College',
  'Linn State Technical College',
  'Linn-Benton Community College',
  'Little Priest Tribal College',
  'Lock Haven University',
  'Loma Linda University',
  'Lone Star College System',
  'Long Beach City College',
  'Long Island University',
  'Longwood University',
  'Lorain County Community College',
  'Loraines Academy Incorporated',
  'Loras College',
  'Los Angeles City College',
  'Los Angeles Community College District',
  'Los Angeles Harbor College',
  'Los Angeles Mission College',
  'Los Angeles Southwest College',
  'Los Angeles Trade-Tech Community College',
  'Los Angeles Valley College',
  'Los Medanos College',
  'Los Rios Community College District',
  'Louisiana Culinary Institute',
  'Louisiana State University System',
  'Louisiana State University – Eunice',
  'Louisiana State University',
  'Louisiana Tech University',
  'Loyola Marymount University',
  'Loyola University Chicago',
  'Loyola University Maryland',
  'Loyola University New Orleans',
  'Lubbock Christian University',
  'Lurleen B. Wallace Community College',
  'Luther College',
  'Luther Seminary',
  'Lycoming College',
  'Lynn University',
  'Lyon College',
  'MGH Institute of Health Professions',
  'Macalester College',
  'Macomb Community College',
  'Madison Area Technical College',
  'Maharishi University of Management',
  'Maine Maritime Academy',
  'Malone University',
  'Manchester Community College',
  'Manchester University',
  'Manhattan College',
  'Manhattanville College',
  'Manor College',
  'Mansfield University',
  'Marian University Indianapolis',
  'Maricopa Community Colleges',
  'Marietta College',
  'Marine Biological Laboratory',
  'Marist College',
  'Marquette University',
  'Marshall University',
  'Marygrove College',
  'Maryland Institute College of Art',
  'Maryland University of Integrative Health',
  'Marylhurst University',
  'Marymount California University',
  'Marymount Manhattan College',
  'Marymount University',
  'Maryville University',
  'Marywood University',
  'MassBay Community College',
  'Massachusetts College of Art and Design',
  'Massachusetts Department of Higher Education',
  'Massachusetts Institute of Technology',
  'Massachusetts Maritime Academy',
  'Mayville State University',
  'McDaniel College',
  'McHenry County College',
  'McKendree University',
  'McLennan Community College',
  'McMurry University',
  'McNally Smith College of Music',
  'McPherson College',
  'Medical College of Wisconsin',
  'Medical University of South Carolina',
  'Merced Community College',
  'Mercer County Community  College',
  'Mercer University',
  'Mercy College',
  'Mercyhurst University',
  'Meridian Technology Center',
  'Merrimack College',
  'Merrimack Education Center',
  'Mesa Community College',
  'Mesabi Range College',
  'Messiah College',
  'Methodist University',
  'Metropolitan College of New York',
  'Metropolitan Community College',
  'Metropolitan State University of Denver',
  'Metropolitan State University',
  'Miami Dade College',
  'Miami International University of Art and Design',
  'Miami University',
  'Michigan State University',
  'Michigan Technological University',
  'Mid-America Christian University',
  'Mid-Pacific Institute',
  'Mid-Plains Community College',
  'Mid-South Community College',
  'Middle Georgia State College',
  'Middle Tennessee State University',
  'Middlebury College',
  'Middlesex Community College',
  'Middlesex County College',
  'Middlesex School',
  'Midland College',
  'Midlands Technical College',
  'Midway College',
  'Midwestern  State University',
  'Midwestern Career College',
  'Midwestern University',
  'Miles Community College',
  'Millennia Atlantic University',
  'Millersville University',
  'Milligan College',
  'Mills College',
  'Milton Academy',
  'Milwaukee Area Technical College',
  'Milwaukee Institute of Art and Design',
  'Milwaukee School of Engineering',
  'Mineral Area College',
  'Minnesota State University Mankato',
  'Minnesota State University Moorhead',
  'Minot State University',
  'MiraCosta College',
  'Misericordia University',
  'Mississippi Gulf Coast Community College',
  'Mississippi State University',
  'Missouri Southern State  University',
  'Missouri State University',
  'Missouri University of Science and Technology',
  'Missouri Valley College',
  'Mizzou University of Missouri',
  'Modesto Junior College',
  'Monmouth College',
  'Monmouth University',
  'Monroe Community College',
  'Monroe County Community College',
  'Montana State University Billings',
  'Montana State University – Northern',
  'Montana State University',
  'Montana Tech of the University of Montana',
  'Montana University System',
  'Montclair State University',
  'Monterey Institute of International Studies',
  'Montgomery Blair High School',
  'Montgomery College',
  'Montgomery Community College',
  'Montgomery County Community College',
  'Montserrat College of Art',
  'Moraine Park Technical College',
  'Moraine Valley Community College',
  'Moravian College',
  'Morehead State University',
  'Morehouse College',
  'Morehouse School of Medicine',
  'Morrisville State College',
  'Morton College',
  'Mount Aloysius College',
  'Mount Holyoke College',
  'Mount Ida College',
  'Mount Marty College',
  'Mount Saint Joseph University',
  'Mount Saint Marry College',
  'Mount Saint Mary’s College',
  'Mount Saint Mary’s University',
  'Mount San Antonio College',
  'Mount San Jacinto College',
  'Mount Vernon Nazarene University',
  'Mount Washington College',
  'Muhlenberg College',
  'Mukogawa Fort Wright Institute',
  'Murray State University',
  'Muskingum University',
  'NHTI Concord’s Community College',
  'Napa Valley College',
  'Naropa University',
  'Nashua Community College',
  'Nashville State Community College',
  'Nassau Community College',
  'National American University',
  'National College of Natural Medicine',
  'National Louis University',
  'National Outdoor Leadership School',
  'National Park Community College',
  'National University of Health Sciences',
  'Naval Postgraduate School',
  'Nazarene Theological Seminary',
  'Nazareth College',
  'Neosho County Community College',
  'Neumann University',
  'New College of Florida',
  'New England College',
  'New England Culinary Institute',
  'New England Institute of Technology',
  'New England Law – Boston',
  'New Jersey City University',
  'New Jersey Institute of Technology',
  'New Life Theological Seminary',
  'New Mexico Highlands University',
  'New Mexico Institute of Mining and Technology',
  'New Mexico State University Alamogordo',
  'New Mexico State University',
  'New Orleans Baptist Theological Seminary',
  'New Paltz',
  'New River Community College',
  'New York College of Health Professions',
  'New York Film Academy',
  'New York Institute of Technology',
  'New York University',
  'NewSchool of Architecture and Design',
  'Newberry College',
  'Newman University',
  'Niagara University',
  'Nicholls State University',
  'Norco College',
  'Norfolk State University',
  'Normandale Community College',
  'North American University',
  'North Arkansas College',
  'North Bennet Street School',
  'North Carolina Central University',
  'North Carolina School of Science and Mathematics',
  'North Carolina State University',
  'North Carolina Wesleyan College',
  'North Central Missouri College',
  'North Central State College',
  'North Central Texas College',
  'North Dakota State University',
  'North Dakota University System',
  'North Florida Community College',
  'North Georgia Technical College',
  'North Greenville University',
  'North Hennepin Community College',
  'North Lake College',
  'North Park University',
  'North Seattle College',
  'Northampton Community College',
  'Northcentral  Technical College',
  'Northeast Alabama Community College',
  'Northeast Community College',
  'Northeast Iowa Community  College',
  'Northeast Mississippi Community College',
  'Northeast Wisconsin Technical College',
  'Northeastern Illinois University',
  'Northeastern State University',
  'Northeastern University',
  'Northern Arizona University',
  'Northern Illinois University',
  'Northern Kentucky University',
  'Northern Maine Community College',
  'Northern Michigan University',
  'Northern New Mexico College',
  'Northern State University',
  'Northern Virginia Community College',
  'Northern Wyoming Community College District',
  'Northland College',
  'Northland Pioneer  College',
  'Northwest Arkansas Community College',
  'Northwest College',
  'Northwest Florida State College',
  'Northwest Missouri State University',
  'Northwest Technical Institute',
  'Northwest-Shoals Community College',
  'Northwestern Michigan College',
  'Northwestern Oklahoma State University',
  'Northwestern University',
  'Norwich  University',
  'Notre Dame de Namur University',
  'Nova Southeastern University',
  'Nunez Community College',
  'Nyack College',
  'Oakland City University',
  'Oakland Community College',
  'Oakland Univeristy',
  'Oakton Community College',
  'Oakwood University',
  'Oberlin College and Conservatory',
  'Occidental College',
  'Ocean County College',
  'Odessa College',
  'Ogle School',
  'Oglethorpe University',
  'Ohio Dominican University',
  'Ohio Northern University',
  'Ohio State University',
  'Ohio State University',
  'Ohio University',
  'Ohio Valley University',
  'Ohio Wesleyan University',
  'Ohlone College',
  'Okefenokee Technical College',
  'Oklahoma Christian University',
  'Oklahoma City Community College',
  'Oklahoma City University',
  'Oklahoma State University Institue of Technology',
  'Oklahoma State University',
  'Oklahoma State University',
  'Old Dominion University',
  'Olin College of Engineering',
  'Olivet Nazarene University',
  'Olympic College',
  'Oral Roberts University',
  'Orange Coast College',
  'Orange County Community College',
  'Orangeburg-Calhoun Technical College',
  'Oregon Health and Science University',
  'Oregon State University',
  'Otis College of Art and Design',
  'Otterbein University',
  'Ouachita Baptist University',
  'Our Lady of the Lake University',
  'Owens Community College',
  'Ozarks Technical Community College',
  'Pace University',
  'Pacific College of Oriental Medicine',
  'Pacific Lutheran Theological Seminary',
  'Pacific Lutheran University',
  'Pacific School of Religion',
  'Pacific University Oregon',
  'Paine College',
  'Palm Beach Atlantic University',
  'Palm Beach State College',
  'Palmer College of Chiropractic',
  'Palomar College',
  'Panola College',
  'Paradise Valley Community College',
  'Park University',
  'Parkland College',
  'Pasadena City College',
  'Pasco-Hernando State College',
  'Passaic County Community College',
  'Patty Hands Shelton School of Nursing',
  'Paul Smith’s College',
  'Pearl River Community College',
  'Pellissippi State Community College',
  'Peninsula College',
  'Penn State University',
  'Pennsylvania Academy of the Fine Arts',
  'Pennsylvania College of Technology',
  'Pennsylvania Gunsmith School',
  'Pensacola State College',
  'Pepperdine University',
  'Peralta Community College District',
  'Perry Technical Institute',
  'Pfeiffer University',
  'Philadelphia College of Osteopathic Medicine',
  'Philadelphia University',
  'Phillips Community College U of A',
  'Phillips Exeter Academy',
  'Phoenix College',
  'Piedmont College',
  'Piedmont Community College',
  'Pierce College',
  'Pierpont Community and Technical College',
  'Pikes Peak Community College',
  'Pima Community College',
  'Pima Medical Institute',
  'Pitt Community College',
  'Pittsburg State University',
  'Pitzer College',
  'Plymouth State University',
  'Point Loma Nazarene University',
  'Pomona College',
  'Porterville College',
  'Portland Community College',
  'Portland State University',
  'Prairie State College',
  'Prairie View A&M University',
  'Pratt Institute',
  'Presbyterian College',
  'Prescott College',
  'Prince George’s Community College',
  'Princeton Theological Seminary',
  'Princeton University',
  'Principia College',
  'Providence College',
  'Pueblo Community College',
  'Pulaski Technical College',
  'Purchase College',
  'Purdue University Calumet',
  'Purdue University North Central',
  'Purdue University',
  'Queens University of Charlotte',
  'Queens University of Charlotte',
  'Quinebaug Valley Community College',
  'Radford University',
  'Ramapo College of New Jersey',
  'Randolph College',
  'Randolph Community College',
  'Randolph-Macon College',
  'Rappahannock Community College',
  'Raritan Valley Community College',
  'Rasmussen College',
  'Reading Area Community College',
  'Red Rocks Community College',
  'Redstone College',
  'Reed College',
  'Reformed Theological Seminary',
  'Regent University',
  'Regis University',
  'Reinhardt University',
  'Rensselaer Polytechnic Institute',
  'Renton Technical College',
  'Resurrection University',
  'Reynolds Community College',
  'Rhode Island College',
  'Rhodes College',
  'Rhose Island School of Design',
  'Rice University',
  'Richland College',
  'Rider University',
  'Ridgewater College',
  'Ringling College of Art and Design',
  'Rio Hondo College',
  'Rio Salado College',
  'Riverside City College',
  'Riverside Community College District',
  'Rivier University',
  'Roane State Community College',
  'Roanoke College',
  'Roanoke-Chowan Community College',
  'Robert Morris University Illinois',
  'Robert Morris University',
  'Roberts Wesleyan College',
  'Rochester Institute of Technology',
  'Rock Valley College',
  'Rockford University',
  'Rockhurst University',
  'Rockland Community College',
  'Rocky Mountain College',
  'Roger Williams University',
  'Rogers State University',
  'Rogue Community College',
  'Rollins College',
  'Roosevelt University',
  'Rosalind Franklin University',
  'Rose State College',
  'Rose-Hulman Institute of Technology',
  'Rosemead College',
  'Ross University',
  'Rowan University',
  'Rutgers University',
  'Sacred Heart University',
  'Saddleback College',
  'Saginaw Chippewa Tribal College',
  'Saginaw Valley State University',
  'Saint Ambrose University',
  'Saint Andrews University',
  'Saint Anselm College',
  'Saint Anthony College of Nursing',
  'Saint Augustine’s University',
  'Saint Bernard’s School of Theology and Ministry',
  'Saint Bonaventure University',
  'Saint Catharine College',
  'Saint Charles Community College',
  'Saint Cloud State  University',
  'Saint Edward’s University',
  'Saint Francis Medical Center College of Nursing',
  'Saint Francis University',
  'Saint James School',
  'Saint John Fisher College',
  'Saint John’s College',
  'Saint John’s College',
  'Saint John’s University',
  'Saint Joseph’s College',
  'Saint Joseph’s University',
  'Saint Lawrence University',
  'Saint Leo University',
  'Saint Louis Community College',
  'Saint Louis University',
  'Saint Martin’s University',
  'Saint Mary’s College of Maryland',
  'Saint Mary’s College',
  'Saint Mary’s College',
  'Saint Mary’s University of Minnesota',
  'Saint Mary’s University',
  'Saint Michael’s College',
  'Saint Norbert College',
  'Saint Olaf College',
  'Saint Paul School of Theology and Ministry',
  'Saint Petersburg College',
  'Saint Thomas University',
  'Saint Vincent College',
  'Saint Vincent Seminary',
  'Saint Vincent de Paul Regional Seminary',
  'Saint Xavier University',
  'Salem College',
  'Salem State University',
  'Salisbury University',
  'Salt Lake Community College',
  'Salus University',
  'Sam Houston State University',
  'Samford University',
  'Sampson Community College',
  'San Bernardino Valley College',
  'San Diego City College',
  'San Diego Mesa College',
  'San Diego State University',
  'San Francisco State University',
  'San Jacinto College',
  'San Joaquin Delta College',
  'San Jose State University',
  'San Juan College',
  'San Mateo County Community College',
  'Sandhills Community College',
  'Santa Ana College',
  'Santa Barbara City College',
  'Santa Clara University',
  'Santa Fe College',
  'Santa Monica College',
  'Santa Rosa Junior College',
  'Sarah Lawrence College',
  'Savannah College of Art and Design',
  'Savannah State University',
  'School for International Training',
  'School of Continuing Education',
  'School of the Art Institute of Chicago',
  'Schreiner University',
  'Scottsdale Community College',
  'Scripps College',
  'Seattle Central College',
  'Seattle Institute of Oriental Medicine',
  'Seattle Pacific University',
  'Seattle University',
  'Seminary of the Southwest',
  'Seminole State College of Florida',
  'Sentara College of Health Sciences',
  'Seton Hall University',
  'Sewanee The University of the South',
  'Shasta College',
  'Shaw University',
  'Shawnee Community College',
  'Shawnee State University',
  'Shenandoah University',
  'Shepherd University',
  'Shippensburg University',
  'Shoreline Community College',
  'Shorter University',
  'Siena College',
  'Sierra College',
  'Sierra Nevada College',
  'Silver Lake College of the Holy Family',
  'Simmons College',
  'Simpson College',
  'Simpson University',
  'Sinclair Community College',
  'Sinte Gleska University',
  'Skagit Valley College',
  'Skidmore College',
  'Skyline College',
  'Slippery Rock University',
  'Smith College',
  'Snead State Community College',
  'Snow College',
  'Sojourner-Douglass College',
  'Soka University of America',
  'Solano Community College',
  'Sonoma State University',
  'South Carolina State University',
  'South Central Career Center',
  'South Central College',
  'South Dakota School of Mines and Technology',
  'South Dakota State University',
  'South Florida State College',
  'South Mountain Community College',
  'South Piedmont Community College',
  'South Plains College',
  'South Seattle College',
  'South Suburban College',
  'South Texas College of Law',
  'South Texas College',
  'Southeast Arkansas College',
  'Southeast Missouri State University',
  'Southeastern Baptist Theological Seminary',
  'Southeastern Bible College',
  'Southeastern Community College',
  'Southeastern Illinois College',
  'Southeastern Louisiana University',
  'Southeastern Oklahoma State University',
  'Southeastern Technical College',
  'Southern Adventist University',
  'Southern Arkansas University Magnolia',
  'Southern California University of Health Sciences',
  'Southern College of Optometry',
  'Southern Connecticut State University',
  'Southern Illinois University Edwardsville',
  'Southern Illinois University',
  'Southern Maine Community College',
  'Southern Methodist University',
  'Southern New Hampshire University',
  'Southern Oregon University',
  'Southern Polytechnic State University',
  'Southern University',
  'Southern Utah University',
  'Southern Virgina University',
  'Southwest Baptist University',
  'Southwest Minnesota State University',
  'Southwest Tennessee Community College',
  'Southwest Virgina Community College',
  'Southwestern Christian University',
  'Southwestern College',
  'Southwestern College',
  'Southwestern Community College',
  'Southwestern Community College',
  'Southwestern Illinois College',
  'Southwestern Oklahoma State Univeristy',
  'Southwestern Oregon Community  College',
  'Southwestern University',
  'Spa Tech Institute',
  'Space Coast Health Institute',
  'Spartanburg Methodist College',
  'Spelman College',
  'Spokane Falls Community College',
  'Spoon River College',
  'Springfield College',
  'Springfield Technical Community College',
  'Stanford University',
  'Stanly Community College',
  'Starr King School for the Ministry',
  'State College of Florida',
  'State University of New Institute of Technology',
  'State University of New York at Adirondack',
  'State University of New York at Oneonta',
  'State University of New York at Oswego',
  'State University of New York at Plattsburgh',
  'State University of New York at Potsdam',
  'State University of New York',
  'Stenotech Career Institute',
  'Stephen F. Austin State University',
  'Sterling College',
  'Stetson University',
  'Stevens Institute of Technology',
  'Stockton College',
  'Stony Brook Medicine',
  'Stony Brook University',
  'Stratford University',
  'Suffolk County Community College',
  'Suffolk University',
  'Sullivan University',
  'Susquehanna University',
  'Sussex County Community College',
  'Swarthmore College',
  'Syracuse University',
  'Taft College',
  'Tarleton State University',
  'Temple College',
  'Temple University',
  'Tennessee State University',
  'Tennessee Technological University',
  'Tennessee Wesleyan College',
  'Texas A&M Health Science Center',
  'Texas A&M International University',
  'Texas A&M University Commerce',
  'Texas A&M University Corpus Christi',
  'Texas A&M University Kingsville',
  'Texas A&M University Texarkana',
  'Texas A&M University',
  'Texas Chiropractic College',
  'Texas Christian University',
  'Texas Southern University',
  'Texas State Technical College',
  'Texas State University',
  'Texas Tech University Health Sciences Center',
  'Texas Tech University',
  'Texas Woman’s University',
  'The  American College of Financial Services',
  'The American Musical and Dramatic Academy',
  'The Art Institute',
  'The Boston Conservatory',
  'The Catholic University of America',
  'The Citadel Military College of South Carolina',
  'The City University of New York',
  'The Claremont Colleges',
  'The College at Brockport',
  'The College of Idaho',
  'The College of New Jersey',
  'The College of New Rochelle',
  'The College of Saint Rose',
  'The College of Saint Scholastica',
  'The College of Westchester',
  'The College of William and Mary',
  'The College of Wooster',
  'The Community College of Baltimore County',
  'The Cooper Union',
  'The Evergreen State College',
  'The General Theological Seminary',
  'The George Washington University',
  'The Hadley School for the Blind',
  'The Institute for the Psychological Sciences',
  'The Institute of Beauty and Wellness',
  'The Institute of Buddhist Studies',
  'The Jewish Theological Seminary',
  'The John Marshall Law School',
  'The Juilliard School',
  'The LeMoyne-Owen College',
  'The Lincoln University',
  'The Master’s College',
  'The New School',
  'The New York Conservatory for Dramatic Arts',
  'The Sages Colleges',
  'The Southern Baptist Theological Seminary',
  'The Touro College and University System',
  'The University of Akron',
  'The University of Chicago Booth School of Business',
  'The University of Findlay',
  'The University of Kansas',
  'The University of Louisville',
  'The University of Memphis',
  'The University of Mississippi',
  'The University of Mount Olive',
  'The University of Oklahoma Health Sciences Center',
  'The University of Oklahoma',
  'The University of Rhode Island',
  'The University of Scranton',
  'The University of Tennessee',
  'Thiel College',
  'Thomas Edison State College',
  'Thomas Jefferson University',
  'Thomas Nelson Community College',
  'Thomas University',
  'Three Rivers Community College',
  'Tidewater Community College',
  'Tiffin University',
  'Tompkins Cortland Community College',
  'Touro College Jacob D. Fuchsberg Law Center',
  'Touro University California',
  'Towson University',
  'Traviss Career Center',
  'Trenholm State Technical College',
  'TriCounty Technical College',
  'Trine University',
  'Trinity Christian College',
  'Trinity College',
  'Trinity University',
  'Troy University',
  'Truckee Meadows Community College',
  'Truman State University',
  'Tufts University',
  'Tulane University',
  'Tulsa Community College',
  'Tunxis Community College',
  'Turtle Mountain Community College',
  'Tuskegee University',
  'Tyler Junior College',
  'UCLA School of Law',
  'Union College',
  'Union College',
  'Union University',
  'United States Military Academy West Point',
  'United States Naval Academy',
  'United Theological Seminary of the Twin Cities',
  'United Tribes Technical College',
  'Unitek College',
  'Unity College',
  'Univeristy of Iowa',
  'Univeristy of New Mexico',
  'University Corporation for Atmospheric Research',
  'University System of Georgia',
  'University System of Maryland',
  'University at Albany',
  'University at Buffalo',
  'University of  Baltimore',
  'University of  Maryland Baltimore County',
  'University of Advancing Technology',
  'University of Alabama at Birmingham',
  'University of Alabama in Huntsville',
  'University of Alabama',
  'University of Alaska Fairbanks',
  'University of Alaska',
  'University of Arizona',
  'University of Arkansas Community College Batesville',
  'University of Arkansas at Little Rock',
  'University of Arkansas at Pine Bluff',
  'University of Arkansas for Medical Sciences',
  'University of Arkansas – Fort Smith',
  'University of Arkansas',
  'University of California Davis',
  'University of California Hastings College of the Law',
  'University of California Irvine',
  'University of California Los Angeles Extension',
  'University of California Los Angeles',
  'University of California Merced',
  'University of California Press',
  'University of California Riverside',
  'University of California San Diego',
  'University of California San Francisco',
  'University of California Santa Barbara',
  'University of California Santa Cruz Silicon Valley Extension',
  'University of California Santa Cruz',
  'University of California Washington Center',
  'University of California',
  'University of California',
  'University of Central Arkansas',
  'University of Central Florida',
  'University of Central Missouri',
  'University of Central Oklahoma',
  'University of Charleston',
  'University of Chicago',
  'University of Cincinnati Blue Ash',
  'University of Cincinnati Clermont',
  'University of Cincinnati',
  'University of Colorado Boulder',
  'University of Colorado Colorado Springs',
  'University of Colorado Denver',
  'University of Colorado',
  'University of Connecticut Health Center',
  'University of Connecticut',
  'University of Dallas',
  'University of Dayton',
  'University of Delaware',
  'University of Denver',
  'University of Detroit Mercy',
  'University of Evansville',
  'University of Florida',
  'University of Georgia',
  'University of Hartford',
  'University of Hawaii at Manoa',
  'University of Houston Clear Lake',
  'University of Houston Downtown',
  'University of Idaho',
  'University of Illinois Springfield',
  'University of Illinois at Chicago',
  'University of Illinois at Urbana-Champaign',
  'University of Illinois at Urbana-Champaign',
  'University of Illinois',
  'University of Indianapolis',
  'University of La Verne',
  'University of Louisiana Lafayette',
  'University of Louisiana at Monroe',
  'University of Main at Augusta',
  'University of Maine Fort Kent',
  'University of Maine at Presque Isle',
  'University of Maine',
  'University of Mary Hardin-Baylor',
  'University of Mary Washington',
  'University of Maryland University College',
  'University of Maryland',
  'University of Maryland',
  'University of Massachusetts Amherst',
  'University of Massachusetts Boston',
  'University of Massachusetts Dartmouth',
  'University of Massachusetts Lowell',
  'University of Massachusetts Medical School',
  'University of Massachusetts',
  'University of Miami',
  'University of Michigan',
  'University of Michigan-Flint',
  'University of Minnesota',
  'University of Mississippi Medical Center',
  'University of Missouri Kansas City',
  'University of Missouri Saint Louis',
  'University of Missouri System',
  'University of Montana Helena College',
  'University of Montana Western',
  'University of Montana',
  'University of Montevallo',
  'University of Mount Union',
  'University of Nebraska Medical Center',
  'University of Nebraska Omaha',
  'University of Nebraska at Kearney',
  'University of Nebraska at Lincoln',
  'University of Nebraska',
  'University of Nevada Las Vegas',
  'University of Nevada Reno',
  'University of New England',
  'University of New Hampshire',
  'University of New Haven',
  'University of New Orleans',
  'University of North Alabama',
  'University of North Carolina Asheville',
  'University of North Carolina Charlotte',
  'University of North Carolina Greensboro',
  'University of North Carolina Pembroke',
  'University of North Carolina School of the Arts',
  'University of North Carolina Wilmington',
  'University of North Carolina at Chapel Hill',
  'University of North Carolina',
  'University of North Dakota',
  'University of North Florida',
  'University of North Georgia',
  'University of North Texas Health Science Center',
  'University of North Texas',
  'University of Northern Colorado',
  'University of Northern Iowa',
  'University of Northwestern Saint Paul',
  'University of Notre Dame',
  'University of Oregon',
  'University of Pennsylvania',
  'University of Phoenix',
  'University of Pittsburgh',
  'University of Portland',
  'University of Puget Sound',
  'University of Redlands',
  'University of Rhode Island',
  'University of Richmond',
  'University of Rio  Grande',
  'University of Rochester',
  'University of Saint Francis',
  'University of Saint Joseph Connecticut',
  'University of Saint Mary',
  'University of Saint Thomas',
  'University of Saint Thomas',
  'University of San Diego',
  'University of San Francisco',
  'University of Science and Arts of Oklahoma',
  'University of Sioux Falls',
  'University of South Alabama',
  'University of South Carolina Aiken',
  'University of South Carolina Beaufort',
  'University of South Carolina Upstate',
  'University of South Carolina',
  'University of South Dakota',
  'University of South Florida Saint Petersburg',
  'University of South Florida Sarasota-Manatee',
  'University of South Florida',
  'University of Southern California',
  'University of Southern Indiana',
  'University of Southern Mississippi',
  'University of Tampa',
  'University of Tennessee Chattanooga',
  'University of Tennessee Health Science Center',
  'University of Tennessee Knoxville',
  'University of Tennessee Martin',
  'University of Tennessee Space Institute',
  'University of Texas Arlington',
  'University of Texas Brownsville',
  'University of Texas Dallas',
  'University of Texas Health Science Center Houston',
  'University of Texas Health Science Center San Antonio',
  'University of Texas Medical Branch at Galveston',
  'University of Texas Pan American',
  'University of Texas Southwestern Medical Center',
  'University of Texas at Austin',
  'University of Texas at El Paso',
  'University of Texas at San Antonio',
  'University of Texas at Tyler',
  'University of Texas of the Permian Basin',
  'University of Toledo',
  'University of Tulsa',
  'University of Utah',
  'University of Vermont',
  'University of Vermont',
  'University of Virginia',
  'University of Virginia’s College at Wise',
  'University of Washington Bothell',
  'University of Washington',
  'University of Washington',
  'University of West Florida',
  'University of West Georgia',
  'University of Wisconsin Colleges',
  'University of Wisconsin Eau Claire',
  'University of Wisconsin Extension',
  'University of Wisconsin Green Bay',
  'University of Wisconsin La Crosse',
  'University of Wisconsin Milwaukee',
  'University of Wisconsin Oshkosh',
  'University of Wisconsin Platteville',
  'University of Wisconsin River Falls',
  'University of Wisconsin Stevens Point',
  'University of Wisconsin Superior',
  'University of Wisconsin Whitewater',
  'University of Wisconsin, Madison',
  'University of Wyoming',
  'University of the Arts',
  'University of the Cumberlands',
  'University of the District of Columbia',
  'University of the Incarnate Word',
  'University of the Ozarks',
  'University of the Pacific',
  'University of the Pacific',
  'University of the Rockies',
  'University of the Sciences in Philadelphia',
  'University of the Southwest',
  'University of the Virgin Islands',
  'Universty of Houston',
  'Upper Iowa University',
  'Upstate  Medical University',
  'Urbana University',
  'Ursinus College',
  'Ursuline College',
  'Utah State University',
  'Utah Valley University',
  'Utica College',
  'Valdosta State University',
  'Valencia College',
  'Valley City State University',
  'Valley Forge Christian College',
  'Valley Grande Institute',
  'Valparaiso University',
  'Vance-Granville Community College',
  'Vanderbilt University',
  'Vanguard University',
  'Vassar College',
  'Ventura College',
  'Vermont Law School',
  'Vermont Technical College',
  'Victor Valley College',
  'Victoria College',
  'Villanova University',
  'Virgina Highlands Community College',
  'Virginia Commonwealth University',
  'Virginia Institute of Marine Science',
  'Virginia International University',
  'Virginia Polytechnic Institute and State University',
  'Virginia State University',
  'Virginia Union University',
  'Virginia Wesleyan College',
  'Virginia Western Community College',
  'Virginia’s Community Colleges',
  'Viterbo University',
  'Volunteer State Community College',
  'Wabash College',
  'Wagner College',
  'Wake Forest University',
  'Wake Technical Community College',
  'Walden University',
  'Waldorf College',
  'Walla Walla Community College',
  'Walla Walla University',
  'Walsh University',
  'Warner Pacific College',
  'Warner University',
  'Warren Wilson College',
  'Wartburg College',
  'Washburn University School of Law',
  'Washburn University',
  'Washington College',
  'Washington State University',
  'Washington University in Saint Louis',
  'Washington and Jefferson  College',
  'Washington and Lee University',
  'Washtenaw Community College',
  'Waubonsee Community College',
  'Waukesha County Technical College',
  'Wayland Baptist University',
  'Wayne State College',
  'Wayne State',
  'Weatherford College',
  'Webber International University',
  'Weber State University',
  'Webster University',
  'Wellesley College',
  'Wells College',
  'Wenatchee Valley College',
  'Wesley College',
  'Wesleyan University',
  'West  Chester University',
  'West Coast Baptist College',
  'West Hills Community College District',
  'West Liberty University',
  'West Los Angeles College',
  'West Texas A&M University',
  'West Valley College',
  'West Virginia Northern Community College',
  'West Virginia State University',
  'West Virginia University',
  'West Virginia Wesleyan College',
  'Westchester Community College',
  'Western Carolina University',
  'Western Connecticut State University',
  'Western Dakota Technical Institute',
  'Western Illinois University',
  'Western Kentucky University',
  'Western Michigan University',
  'Western Nevada College',
  'Western New England University',
  'Western Oklahoma State College',
  'Western Oregon University',
  'Western Piedmont Community College',
  'Western Reserve University',
  'Western State Colorado University',
  'Western Technical College',
  'Western University of Health Sciences',
  'Western Washington University',
  'Westminster College',
  'Westminster College, Missouri',
  'Westmont College',
  'Westmoreland County Community College',
  'Wheaton College',
  'Wheaton College, Norton',
  'Wheeling Jesuit University',
  'Wheelock College',
  'White Mountains Community College',
  'Whitman College',
  'Whittier College',
  'Whitworth University',
  'Wichita State University',
  'Widener University',
  'Wilkes University',
  'Willamette University',
  'William Carey University',
  'William Howard Taft University',
  'William Jessup University',
  'William Paterson University',
  'Williams Baptist College',
  'Williams College',
  'Williston State College',
  'Wilmington College',
  'Wilmington University',
  'Wilson College',
  'Winona State Unviversity',
  'Winston-Salem State University',
  'Winthrop University',
  'Wiregrass Georgia Technical College',
  'Wisconsin Indianhead Technical College',
  'Wisconsin Lutheran College',
  'Wisconsin Technical College System',
  'Wittenberg University',
  'Wofford College',
  'Wor-Wic Community College',
  'Worcester Polytechnic Institute',
  'Worcester State University',
  'Wright State University',
  'Xavier University of Louisiana',
  'Xavier University',
  'Yakima Valley Community College',
  'Yale University',
  'Yavapai College',
  'Yeshiva University',
  'York College of Pennsylvania',
  'York County Community College',
  'York Technical College',
  'Yosemite Community College District',
  'Youngstown State University',
  'Yuba Community College District'
]);

module.exports = usUniversity;
